[cmd_duration]
show_milliseconds = true
min_time = 1000

[directory]
truncation_symbol = "…"

[git_status]
disabled = true

[package]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[status]
disabled = false

[time]
disabled = false
# use_12hr = true
time_format = "%-I:%M:%S %p"
