if filereadable(expand("~/.gvimrc.pre-local"))
  source ~/.gvimrc.pre-local
endif

set go-=T
set bg=dark

if &background == "dark"
    hi normal guibg=black
endif

if &diff
    set columns=178
else
    set columns=89
endif

set guifont=Bitstream\ Vera\ Sans\ Mono\ 8 

colorscheme ir_black

"set guioptions+=c

"set guioptions-=m
"set guioptions-=T
"set guioptions-=r
"set guioptions-=R
"set guioptions-=l
"set guioptions-=L
"set guioptions-=b
"set guioptions+=p

set guioptions+=c " Console Dialogs
set guioptions+=b " Bottom scrollbar
set guioptions+=m " Menu Bar
set guioptions+=p " x11 pointer callbacks


" egtcp
" gcp  e t
" gcpbaemt

map <silent> <F2> :if &guioptions =~# 'T' <Bar>                                        x
            \set guioptions-=T <Bar>
            \set guioptions-=m <bar>
            \else <Bar>
            \set guioptions+=T <Bar>
            \set guioptions+=m <Bar>
            \endif<CR>

"hi Cursor guifg=white guibg=Red
"hi iCursor guifg=white guibg=Red
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver20-Cursor-blinkon600-blinkoff600
set guicursor+=n-v-c:block-Cursor-blinkon600-blinkoff600
"set guicursor+=n-v-c:blinkon0

set columns=116

" esc in normal mode clears search highlighting
nnoremap <silent> <ESC>:nohl<CR><ESC>


if filereadable(expand("~/.gvimrc.post-local"))
  source ~/.gvimrc.post-local
endif
