if filereadable(expand("~/.gvimrc.pre-local"))
  source ~/.gvimrc.pre-local
endif

set go-=T
set bg=dark

" if &background == "dark"
    " hi normal guibg=black
" endif

if &diff
    set columns=178
else
    set columns=89
endif

set guifont=Bitstream\ Vera\ Sans\ Mono\ 8 

" colorscheme ir_black
" colorscheme mustang

set guioptions-=a " autoselect
set guioptions-=A " autoselect
set guioptions+=c " Console Dialogs
set guioptions-=e " tab stuff
set guioptions+=f " forking
set guioptions-=i " icon
set guioptions-=m " menu bar
set guioptions-=M " system menu
set guioptions-=g " grey menu items
set guioptions-=t " include tearoff menu items
set guioptions-=T " toolbar
set guioptions-=r " right scrollbar
set guioptions-=R " right scrollbar on split
set guioptions-=l " left scrollbar
set guioptions-=L " left scrollbar on split
set guioptions-=b " bottom scrollbar
set guioptions-=h " limit horizontal scrollbar size
set guioptions-=v " vertical button layout for dialogs
set guioptions+=p " x11 pointer callbacks
set guioptions-=F " motif footer

map <silent> <F2> :if &guioptions =~# 'T' <Bar>                                        x
            \set guioptions-=T <Bar>
            \set guioptions-=m <bar>
            \else <Bar>
            \set guioptions+=T <Bar>
            \set guioptions+=m <Bar>
            \endif<CR>

"hi Cursor guifg=white guibg=Red
"hi iCursor guifg=white guibg=Red
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver20-Cursor-blinkon600-blinkoff600
set guicursor+=n-v-c:block-Cursor-blinkon600-blinkoff600
"set guicursor+=n-v-c:blinkon0

set columns=116

" esc in normal mode clears search highlighting
nnoremap <silent> <ESC> :nohl<CR><ESC>


if filereadable(expand("~/.gvimrc.post-local"))
  source ~/.gvimrc.post-local
endif
