set go-=T

if &diff
    set columns=178
else
    set columns=89
endif

set guifont=Bitstream\ Vera\ Sans\ Mono\ 10

set guioptions-=a " autoselect
set guioptions-=A " autoselect
set guioptions+=c " Console Dialogs
set guioptions-=e " tab stuff
set guioptions+=f " forking
set guioptions-=i " icon
set guioptions-=m " menu bar
set guioptions-=M " system menu
set guioptions-=g " grey menu items
set guioptions-=t " include tearoff menu items
set guioptions-=T " toolbar
set guioptions-=r " right scrollbar
set guioptions-=R " right scrollbar on split
set guioptions-=l " left scrollbar
set guioptions-=L " left scrollbar on split
set guioptions-=b " bottom scrollbar
set guioptions-=h " limit horizontal scrollbar size
set guioptions-=v " vertical button layout for dialogs
set guioptions+=p " x11 pointer callbacks
set guioptions-=F " motif footer

map <silent> <F2> :if &guioptions =~# 'T' <Bar>                                        x
            \set guioptions-=T <Bar>
            \set guioptions-=m <bar>
            \else <Bar>
            \set guioptions+=T <Bar>
            \set guioptions+=m <Bar>
            \endif<CR>

set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver20-Cursor-blinkon600-blinkoff600
set guicursor+=n-v-c:block-Cursor-blinkon600-blinkoff600

set columns=116

" esc in normal mode clears search highlighting
nnoremap <silent> <ESC> :nohl<CR><ESC>

set background=dark
colorscheme distinguished
hi SignColumn    ctermfg=10 ctermbg=0 guifg=#586e75 guibg=#073642"
hi ShowMarksHLl  ctermfg=1 ctermbg=0 guifg=#586e75 guibg=#073642"
hi ShowMarksHLu  ctermfg=9 ctermbg=0 guifg=#cb4b16 guibg=#073642"
hi ShowMarksHLo  ctermfg=5 ctermbg=0 guifg=#d33682 guibg=#073642"
hi ShowMarksHLm  ctermfg=6 ctermbg=0 guifg=#2aa198 guibg=#073642"
