#!/bin/sh
# Set the background
feh --bg-scale --no-fehbg $HOME/Pictures/Sleeper-manip.jpg

# Start the compositing manager
xcompmgr -Ffn &

# Hide mouse when idle
unclutter -idle 1 &

# Start the urxvt daemon
urxvt256cd -q -f -o
