#!/usr/bin/env python
import re
import sys
import os
import datetime
import subprocess

def get_uptime():
    with open('/proc/uptime', 'r') as f:
        data = f.readline().split()[0]
    return float(data)

def main():
    os.environ['PATH'] = '/bin'
    try:
        uptime = get_uptime()
    except IOError:
        os.system('dmesg')
    else:
        boottime = datetime.datetime.now() - datetime.timedelta(0, uptime)
        cmd = subprocess.Popen('dmesg', stdout=subprocess.PIPE)
        for line in cmd.stdout.readlines():
            m = re.match('\[\s*(\d+\.\d+)\] (.*)$', line) 
            if m:
                t = boottime + datetime.timedelta(0, float(m.group(1)))
                print '[%s] %s' % (t, m.group(2))
            else:
                print '                             %s' % (line.rstrip("\n"),)
        exit_code = os.waitpid(cmd.pid, 0)[1]
        return exit_code



if __name__ == '__main__':
    sys.exit(main())
