#!/usr/bin/env python
# encoding: utf-8
import re
import sys
import os

DRIVEL_FILE = os.path.join(os.path.dirname(__file__), 'drivel.tsv')

def read_drivel():
    drivel = []
    with open(DRIVEL_FILE) as fh:
        for line in fh.read().strip().split("\n"):
            word, recommendation = line.split("\t")
            drivel.append((r'\b%s\b' % word, word, recommendation))
    # Work from longest to shortest pattern to prevent duplicates from one
    # pattern being a substring of another.
    return reversed(sorted(drivel, key=lambda x: len(x[0])))

def check(fhandle):
    drivel = read_drivel()
    # TODO: Make this into a stream processor
    text = re.sub(r'\s+', ' ', fhandle.read())
    for pattern, word, recommendation in drivel:
        m = re.search(pattern, text)
        if m:
            print("%s => %s" % (word, recommendation))
            # Remove the pattern we found before searching for the next
            # pattern.
            text =  text[:m.start()] + text[m.end():]

def main():
    check(sys.stdin)

if __name__ == '__main__':
    main()

