#!/bin/sh

NEW=0
DIR=$(pwd)
NAME=4x4

set -- $(getopt -o nd:N: --long new,dir:,name:"$@")
while [ $# -gt 0 ]
do
    echo "1: $1"
    case "$1" in
        (-n|--new) NEW=1
                   ;;
        (-d|--dir) NEW=1
                   DIR=$2
                   shift
                   ;;
        (-N|--name) NEW=1
                    NAME=$2
                   shift
                    ;;
        (--) shift
             break
             ;;
        (*)  echo "$0: error - unrecognized option $1" 1>&2
             exit 1
             ;;
    esac
    shift
done

[ $NEW -eq 1 ] && tmux new-window -c $DIR -n $NAME

tmux split-window -h -c $DIR
tmux split-window -h -c $DIR
tmux split-window -c $DIR
tmux select-pane -t 2
tmux split-window -c $DIR
tmux select-pane -t 1
tmux split-window -c $DIR
tmux split-window -h -c $DIR
tmux select-pane -t 1
tmux split-window -h -c $DIR
tmux select-pane -t 1
tmux split-window -c $DIR
tmux select-pane -t 3
tmux split-window -c $DIR
tmux select-pane -t 5
tmux split-window -c $DIR
tmux select-pane -t 7
tmux split-window -c $DIR
tmux select-pane -t 9
tmux split-window -c $DIR
tmux select-pane -t 11
tmux split-window -c $DIR
tmux select-pane -t 13
tmux split-window -c $DIR
tmux select-pane -t 15
tmux split-window -c $DIR
tmux select-pane -t 1
