#!/bin/sh

tmux split-window -h
tmux split-window -h
tmux split-window
tmux select-pane -t 2
tmux split-window
tmux select-pane -t 1
tmux split-window
tmux split-window -h
tmux select-pane -t 1
tmux split-window -h
tmux select-pane -t 1
