#!/bin/sh
if [ -r TODO ]; then
    echo "TODO:"
    cat -n TODO
fi
if [ -r TODO.md ]; then
    echo "TODO.md:"
    cat -n TODO.md
fi
if [ -r TODO.rst ]; then
    echo "TODO.rst:"
    cat -n TODO.rst
fi
ack "TODO|FIXME|REVIEW|XXX"
