#!/bin/sh

if [ -x /usr/bin/pmset ]; then
    # Query for battery status
    status=$(pmset -g batt)
    echo $status | awk \
        '/; discharging/ { 
            if (int($7) > 0) 
                print "#[fg=red]" int($7) "%#[default] " 
        } 
        /; charging/ { 
            if (int($7) > 0) 
                print "#[fg=green]" int($7) "%#[default] " 
        }'
fi
