#!/bin/sh
DIR=$(pwd)
tmux select-pane -t 0
tmux split-window -d -h -l 81
WIDTH=$(stty size | cut -d' ' -f2)
tmux split-window -h -l $(($WIDTH-81))
tmux split-window -d -v -l 10
for id in $(tmux list-panes | cut -d':' -f1); do
    tmux send-keys -t $id "cd $DIR" C-m
done
