#!/usr/bin/env python
#
#   Last edited by:  $Author$
#               on:  $Date$
#         Source  :  $Source$
#         Revision:  $Revision$
#
#               ID:  $Id$

import sys
import os
import pprint

from optparse import OptionParser

__version__ = "$Revision: 0 $"[11:-2]

def main():
    options, args = parse_options()
    cmdargs = ['\gvim']
    if options.foreground and options.remote:
        cmdargs.append('--remote-wait')
    elif options.remote:
        cmdargs.append('--remote')
    elif options.foreground:
        cmdargs.append('-f')
    for arg in args:
        cmdargs.append(arg)
    #pprint.pprint(cmdargs)
    try:
        sys.exit(os.system(' '.join(cmdargs)))
    except KeyboardInterrupt:
        sys.exit(1)

def parse_options():
    """Process Commandline Arguments"""
    p = OptionParser()
    p.add_option('-f', action='store_true', dest='foreground',
            default=False, help='run in foreground')
    p.add_option('--remote', action='store_true', dest='remote',
            default=True, help='use existing session')
    (options, args) = p.parse_args()
    if len(args) == 0:
        options.remote= False
    return (options, args)

if __name__ == '__main__':
    main()

# vim: set ft=python ts=4 sw=4 et:

