#!/bin/sh
set -e
if [ -z "$1" ]; then
    echo "git-export <dir>" > /dev/stderr
    exit 1
fi

if [ -d "$1" ]; then
    echo "$1 already exists" > /dev/stderr
    exit 1
fi

mkdir -p "$1"
git archive master | tar -x -C "$1"

