#!/bin/sh

if [ $# -ne 1 ]; then
   echo 1>&2 Usage: $0 branch_name
   exit 127
fi

branch_name=$1

git branch -r | grep "origin/${branch_name}$" > /dev/null 2>&1
if [ $? == 0 ]; then
   echo 1>&2 Remote branch \`${branch_name}\` already exists
   exit 127
fi

git push origin origin:refs/heads/${branch_name}
if [ $? != 0 ]; then
   echo 1>&2 Unable to create remote branch \`${branch_name}\`
   exit 127
fi

git fetch origin
if [ $? != 0 ]; then
   echo 1>&2 Unable to fetch updates from origin
   exit 127
fi

git checkout --track -b ${branch_name} origin/${branch_name}
if [ $? != 0 ]; then
   echo 1>&2 Unable to setup local tracking of remote branch \`${branch_name}\`
   exit 127
fi

git pull
if [ $? != 0 ]; then
   echo 1>&2 Unable to pull updates from origin
   exit 127
fi
