#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

if [ "$branch" = "" ]; then
    echo "Not in a git repository." > /dev/stderr
    exit 1
fi

remote=${1:-origin}

git branch --set-upstream-to $remote $branch
