#!/bin/sh

function cores() {
    n=0
    exec 0</proc/cpuinfo
    while read line; do
        i=$(echo $line | grep cores | cut -d: -f2)
        if [ ! -z $i ]; then
            n=$(($n+$i))
        fi
    done
    echo $n
}

uname -nr
echo
uptime | sed 's/^\s*//'
echo
echo "Cores: $(cores)"
echo
cat <<EOF
Legend:
  Displayed:
   D    Uninterruptible sleep (usually IO)
   R    Running or runnable (on run queue)
   X    dead (should never be seen)
 ----------------------------------
   <    high-priority (not nice to other users)
   N    low-priority (nice to other users)
   L    has pages locked into memory (for real-time and custom IO)
   s    is a session leader
   l    is multi-threaded (using CLONE_THREAD, like NPTL pthreads do)
   +    is in the foreground process group
EOF
echo
ps -NTo stat,pcpu,pmem,pid,ppid,user,args | grep -vE "^[WSTZ][ NLsl+<]" || echo "N/A"

