#!/bin/sh
uptime | sed 's/^\s*//'
echo
echo "Processes:"
ps -eo state,pcpu,pid,user,args | grep -vE '^[ZS]' | sort -k1 | sort -k2nr


cat <<EOF

Legend:
   D    Uninterruptible sleep (usually IO)
   R    Running or runnable (on run queue)
   S    Interruptible sleep (waiting for an event to complete)
   T    Stopped, either by a job control signal or because it is being
        traced.
   W    paging (not valid since the 2.6.xx kernel)
   X    dead (should never be seen)
   Z    Defunct ("zombie") process, terminated but not reaped by its
        parent.
EOF
