#!/usr/bin/env python

import sys
import time

def main():
    line = sys.stdin.readline()
    year = time.gmtime().tm_year
    while line != '':
        ts = time.strptime("{0} {1}".format(year, line[0:15]), "%Y %b %d %H:%M:%S")
        ts = time.mktime(ts)
        ts = int(ts)
        print("{0} {1}".format(ts, line[16:].rstrip()))
        line = sys.stdin.readline()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit(1)
