#!/bin/sh
if [ ! -z "$1" ]; then
    echo "$1" | grep '^/' > /dev/null 2>&1
    if [ $? == 0 ]; then
        FILE="$1"
    else
        FILE="`pwd`/$1"
    fi
    COMMAND=":botright split $FILE<CR>"
    gvim --remote-send "$COMMAND" > /dev/null 2>&1
    if [ $? != 0 ]; then
        gvim $FILE
    fi
fi
