#!/bin/sh
ACTION=$1
if [ -z "$1" ]; then
    status=$(tmux show-window-options synchronize-panes | cut -d' ' -f2)
    if [ "$status" = "on" ]; then
        ACTION=off
    else
        ACTION=on
    fi
fi
tmux set-window-option synchronize-panes $ACTION
