#!/bin/sh
set -e

function enable() {
    tmux set-window-option -g mode-mouse on 2>&1 | grep -q on
    tmux set-window-option -g mouse-resize-pane on 2>&1 | grep -q on
    tmux set-window-option -g mouse-select-pane on 2>&1 | grep -q on
    tmux set-window-option -g mouse-select-window on 2>&1 | grep -q on
    tmux set-window-option -g mouse-utf8 on 2>&1 | grep -q on
    tmux display 'Mouse: ON'
}

function disable() {
    tmux set-window-option -g mode-mouse off 2>&1 | grep -q off
    tmux set-window-option -g mouse-resize-pane off 2>&1 | grep -q off
    tmux set-window-option -g mouse-select-pane off 2>&1 | grep -q off
    tmux set-window-option -g mouse-select-window off 2>&1 | grep -q off
    tmux set-window-option -g mouse-utf8 off 2>&1 | grep -q off
    tmux display 'Mouse: OFF'
}

function status() {
    mstatus=$(tmux show-window-options -g | grep mode-mouse | cut -d' ' -f2)
    if [ "$mstatus" = "off" ]; then
        echo 'Mouse: OFF'
        tmux display 'Mouse: OFF'
    else
        echo 'Mouse: ON'
        tmux display 'Mouse: ON'
    fi
}

function toggle() {
    mstatus=$(tmux show-window-options -g | grep mode-mouse | cut -d' ' -f2)
    if [ "$mstatus" = "off" ]; then
        enable
    else
        disable
    fi
}

if [ "$1" = "on" ]; then
    enable
elif [ "$1" = "off" ]; then
    disable
elif [ "$1" = "status" ]; then
    status
else
    toggle
fi
