#!/bin/sh
if [ -f /usr/local/bin/reattach-to-user-namespace ]; then
    tmux bind C-c run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
    tmux bind C-v run "tmux set-buffer $(reattach-to-user-namespace pbpaste); tmux paste-buffer"
    exec "reattach-to-user-namespace -l $SHELL"
else
    exec $SHELL
fi
