#!/usr/bin/env python
'''${cmd}

Usage: ${cmd} [-v | -vv] ${args}
       ${cmd} -h | --help
       ${cmd} --version

Options:
	-h --help          Show this screen.
	--version          Show version.    
	-v --verbose       Increase verbosity
	${option}
'''

from __future__ import print_function
from __future__ import division
from __future__ import absolute_import
from __future__ import unicode_literals

import docopt
import logging
import os
import sys

LOG = logging.getLogger(__name__)
__prog__ = '${cmd}'
__version__ = '1.0.0'


def main():
    '''
    Main program logic
    '''
    args = docopt.docopt(__doc__, version='%s %s' % (__prog__, __version__))
    ${# code}
    return 0

if __name__ == '__main__':
	sys.exit(main())
